apiVersion: v1
kind: Pod
metadata:
  name: test-shortrange01
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-test-conf
spec:
  containers:
  - name: test-shortrange01
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: test-shortrange02
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-test-conf
spec:
  containers:
  - name: test-shortrange02
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: test-shortrange03
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-test-conf
spec:
  containers:
  - name: test-shortrange03
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
    